### ISSUE TITLE
WH32 support

### ISSUE THREAD

**Issue by cschacht** [bzwan/homebridge-ecowitt#2]
Hi, 

thanks for the great work @bzwan! 

Seems to be an long open issue with the original implementation by @spacialdude: 
https://github.com/spatialdude/homebridge-ecowitt/issues/2 

about support for the WH32 outdoor sensor. 

This seems to be the most active branch of the plugin. Would it be possible to include support for this sensor in one of the next releases? 

Thanks
Chris

**Comment by bzwan** [comment]
I can give it a try... I assume the options on the WH32 are identical to the WH31?

**Comment by bzwan** [comment]
Do you get any detailed error messages when you add the WH32?

**Comment by cschacht** [comment]
In the plugin config I don't see any option to add the WH32 sensor, where can I do that? 

The sensor is added to the gateway and I can see the data on the app. In home bridge I don't get any error message but also no output indicating that it has read the sensor data.

**Comment by bzwan** [comment]
OK, that probably makes sense. Let me add something and create you an updates version...

**Comment by bzwan** [comment]
Can you run the HomeBridge service in debug mode and copy the DataReport log entry for me here?

**Comment by bzwan** [comment]
Please update to the latest version (1.1.61) and let me know if that works. It's a bit of a gamble as I don't have the WH32 sensor myself. So if it doesn't work you can at least give me the logs. Please let me know the results.

**Comment by cschacht** [comment]
Thanks @bzwan, 

it didn't work but here's the data report from the log: 

[06/06/2023, 08:40:10] [Ecowitt] Data report: {
  "PASSKEY": "XXXX",
  "stationtype": "GW1000A_V1.7.6",
  "runtime": "160027",
  "dateutc": "2023-06-06 06:40:10",
  "tempinf": "72.14",
  "humidityin": "66",
  "baromrelin": "30.002",
  "baromabsin": "30.002",
  "tempf": "60.08",
  "humidity": "76",
  "soilmoisture1": "66",
  "soilmoisture2": "70",
  "soilmoisture4": "25",
  "soilmoisture6": "70",
  "soilmoisture8": "52",
  "wh26batt": "0",
  "soilbatt1": "1.5",
  "soilbatt2": "1.3",
  "soilbatt4": "1.3",
  "soilbatt6": "1.5",
  "soilbatt8": "1.3",
  "freq": "868M",
  "model": "GW1000A_Pro"
}

Seems the outdoor temperature is in 'tempf' and outdoor humidity in 'humidity' data.

**Comment by bzwan** [comment]
Thx. Did you get an error message? Can you share the full log with me, in debug mode?

**Comment by bzwan** [comment]
Ok, I think I found the issue but we can only be sure if you test it again. Please update to the latest version and try again.

**Comment by cschacht** [comment]
It works! Fantastic! 

Just one more thing, it seems that the air pressure data is mapped to a presence detection sensor in Apple Home. In the Homebridge UI I can see both absolute and relative air pressure but in the Home App this is shown as a binary sensor present/not present. 

Any thoughts? 

Many thanks for the quick solution! 🙏🏻😀

**Comment by bzwan** [comment]
Great!
I have the same with the barometer sensors. Apple Home just doesn't show them. The only way you can use them is by adding them in an automation when they reach a certain treshold. Home kit is a little limited like that.

**Comment by cschacht** [comment]
ok, thanks for this super fast turn-around time!

**Comment by cschacht** [comment]
@bzwan just one more thing: In the home bridge log I get this message: 

[07/06/2023, 09:31:41] [Ecowitt] Updating: WH32 channel: **undefined**
[07/06/2023, 09:31:41] [Ecowitt] WH32 Update

All seems to be working fine but Is this "undefined" message of any concern?

**Comment by bzwan** [comment]
That shouldn't be a problem. It's trying to log the channel of the sensor like with the WH31 which has up to 8 channels. The WH32 doesn't have any channels hence the "undefined". You should probably see a similar message for your GW1000 station... Nothing to worry about.
